name: 编译micromamba并推送到DockerHub 

on:
  push:
    branches:
      - 'master'
    paths:
      - 'Dockerfile/dependent'

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: my-docker-image
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  push_to_registry:
    name: 编译micromamba并推送到DockerHub 
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 登录docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: 设置 Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: 获取时间
        run: echo "TRIGGER_TIME=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: 编译镜像
        uses: docker/build-push-action@v2
        with:
          context: ./Dockerfile
          dockerfile: micromamba
          push: true
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          platforms: linux/amd64
          tags: |
            eclairkk/dependent:${{ env.TRIGGER_TIME }}
            eclairkk/dependent:latest
