# docker-image.yml
name: Publish Docker image   # workflow名称，可以在Github项目主页的【Actions】中看到所有的workflow

on:   # 配置触发workflow的事件
  push:
    branches:   # master分支有push时触发此workflow
      - 'master'
    tags:       # tag更新时触发此workflow
      - '*'

jobs:  # workflow中的job

  push_to_registry:  # job的名字
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest   # job运行的基础环境

    steps:  # 一个job由一个或多个step组成
      - uses: actions/checkout@v3   # 官方的action 从GitHub仓库中检出代码

      - name: Get the version # 获取代码中的版本信息
        id: vars # 将版本信息设置为输出变量1
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:14})

      - name: Login to DockerHub // 登录到DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} // DockerHub用于认证和授权的用户名
          password: ${{ secrets.DOCKER_PASSWORD }} // 对应的密码

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3  # 抽取项目信息，主要是镜像的tag
        with:
          images: jhao104/proxy_pool

      - name: Build # 使用Docker Buildx构建并推送Docker镜像
        uses: docker/build-push-action@v4 

        with:
          context: .
          push: true # 是否将构建好的镜像推送到仓库
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
