name: Publish Docker image

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: my-docker-image
  DOCKER_IMAGE_TAG: ${{ github.sha }}


jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # 官方的action 从GitHub仓库中检出代码1
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录docker
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ env.DOCKER_REGISTRY }}

      # Docker Buildx 插件，以便于构建多平台镜像
      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: 编译上传docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            eclairkk/sd:23.4.19
            eclairkk/sd:latest
