name: 发布 micromamba 镜像

on:
  push:
    branches:
      - 'master'
    paths:
      - 'micromamba'

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 登录docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: 设置 Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        

      - name: 获取时间
        # run: echo "WEATHER_REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
        run: echo "WEATHER_REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: 编译上传
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          platforms: linux/amd64
          tags: |
            eclairkk/sd:${{ github.event_time }}
            eclairkk/sd:latest
